baseURL = 'https://github.com/tze-min/occurrence-mapper-app'
languageCode = 'en-us'
author = 'Tze Min'
copyright = "Copyright © 2022"
title = 'Occurrence Mapper'
theme = "hugo-theme-tokiwa" 

[params]
bannerFont = "fonts/exampleFont" 
useChineseFonts = true # keep this true for nicer font
description = """
A dashboard app that maps and visualises species occurrence data.
"""  
env = "production"
math = true # for introducing $KaTEX$
postDateFormat = "2 Jan 2006"

[menu]
# Shown in the side menu.
  [[menu.main]]
	identifier = "post"
	name = "Posts"
	url = "/posts/"
	weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
  	name = "Tags"
  	url = "/tags/"
  	weight = 3

[social]
github = "http://github.com/tze-min/occurrence-mapper-app"
linkedin = "http://linkedin.com/koaytzemin"


[outputs]
home = ["HTML", "RSS", "JSON"]